version: 1
disable_existing_loggers: True
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file-format:
        format: "%(asctime)s - %(levelname)s - [%(name)s] - [%(module)s] - %(funcName)s() - %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:

    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        formatter: file-format
        level: "DEBUG"
        filename: "/tmp/logs/log.log"
        maxBytes: 1000
        backupCount: 20
        encoding: utf8

loggers:

  "":
      handlers: ['console']
      level: 'INFO'
      propagate: False

  "stats":
      handlers: ['file_handler']
      level: "DEBUG"
      propagate: False

  py.warnings:
      handlers: ['file_handler']
      level: 'INFO'
      propagate: True
