version: 1
disable_existing_loggers: True
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

params:
    path: &path '/Users/deusebio/work/projects/cgnal/git/logging-test/logs'
    rot_file_handler:
        class: &rotating logging.handlers.RotatingFileHandler
        maxBytes: &maxBytes 10485760 # 10MB
    stream_handler: &stream logging.StreamHandler

handlers:

    info_file_handler:
        class: *rotating
        formatter: simple
        filename: !joinPath [*path, "info.log"]
        maxBytes: *maxBytes
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: *rotating
        level: ERROR
        formatter: simple
        filename: !joinPath [*path, "error.log"]
        maxBytes: *maxBytes
        backupCount: 20
        encoding: utf8

    warn_file_handler:
        class: *rotating
        level: WARN
        formatter: simple
        filename: !joinPath [*path, "warn.log"]
        maxBytes: 5242880
        backupCount: 2
        encoding: utf8


loggers:

  "":
      handlers: ['info_file_handler', 'error_file_handler']
      level: 'DEBUG'
      propagate: False

  "stats":
      handlers: ['info_file_handler', 'error_file_handler']
      level: "INFO"
      propagate: False

  py.warnings:
      handlers: ['warn_file_handler']
      level: 'INFO'
      propagate: True
